### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by phoe** [vygr/ChrysaLisp#1]
Do you have any screenshots that showcase the OS as it's working, even if it's console-only?

**Comment by vygr** [comment]
Screen Shot png in with the project. Hope this link works for you.

https://github.com/vygr/ChrysaLisp/blob/master/Screen%20Shot.png

Chris

**Comment by vygr** [comment]
The Terminal app you see on the screen shot is also available as a stand alone text user interface without any of the GUI. Most of my development I spend using the TUI, for building etc.

Regards

Chris
