### ISSUE TITLE
Leverage stage0?

### ISSUE THREAD

**Issue by no-identd** [vygr/ChrysaLisp#10]
You can find @oriansj's stage0 repository here:

https://github.com/oriansj/stage0

And more details here:

https://github.com/oriansj/stage0/blob/master/bootstrapping%20Steps.org

Even more details here:

http://bootstrappable.org/

And here:
https://www.freelists.org/archive/bootstrappable/

I hope why I make this suggestion will seem obvious. If it doesn't, please let me know. 🙂

**Comment by vygr** [comment]
Yes, I will look at this :)

This comment made me ROTFL. I've been there myself :) "If you want to bootstrap anything, NEVER EVER EVER START WITH FORTH."

Forth, the biggest mind bending brain fuck ever. Writing a Forth compiler will suck your brain out through a straw and put it back scrambled. But the pain was oh so good that you feel that you learnt something very deep, but it's difficult to express, like a brain enema. Chuck Moore, genius.

Regards

Chris

**Comment by DKordic** [comment]
`only Forth` awaits thy at the end of the last closing parenthesis.

**Comment by DKordic** [comment]
`stage0` is a stupid joke.  Issue #10 closed.

**Comment by vygr** [comment]
:)

**Comment by no-identd** [comment]
It neither represents a joke nor anything stupid, @DKordic, nor did my suggestion. Either one wants a system one can trust, or one doesn't. Apparently you don't realize the value of it, but it has value, and dismissing it like this seems highly childish & immature.

**Comment by no-identd** [comment]
Maybe you'd want to watch this (by now rather outdated, but still useful) video on MES, which goes beyond stage0 (and is thus not entirely independent, as it's aimed at GNU Guix and hence targets Scheme. Obviously, ChrysaLisp would need a version of it for ChrysaLisp, not Scheme, but the points stand), to understand the point behind this a bit better:

https://www.youtube.com/watch?v=7NFD_9d7J3Q

Maybe also try googling "trusting trust problem" to understand why one can't, on a logical level, trust a system that hasn't fully bootstrapped from the ground up.

**Comment by no-identd** [comment]
Better video:

https://www.youtube.com/watch?v=mhopx8J2Z8s
