### ISSUE TITLE
merge behavior

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#115]
There may be some nuance I'm not aware, but found this:

```
(merge '(:a 0 :b 1) '(:c 2 :a 3))
; (:a 0 :b 1 :c 2 3) <- Note missing second ':a'
; expected
; (:a 0 :b 1 :c 2 :a 3)
```

**Comment by vygr** [comment]
The low level (merge) is a pointer equality merge. So for symbols or interned objects.

**Comment by vygr** [comment]
Merge would not lead to 2 instances of :a in your example. That's not a merged outcome ? There should only be 1 :a.

**Comment by vygr** [comment]
It's action is a union of a set of object references.

**Comment by vygr** [comment]
Is this in conflict with some established standard for (merge) ? If so I'll rename us to (union) and leave the merge name for some other action ?

**Comment by FrankC01** [comment]
Yes, the signature and behavior is different than [Common Lisp](http://clhs.lisp.se/Body/f_merge.htm) in a few ways.

So if the intent to do a union, then naming it that would not be bad and would support expectations. However; I realize that you are not trying to exactly align to a Lisp standard so there will be that disconnect for those expecting same named functions with other Lisp to behave the same way. I know that no one likes doing it but having a bit more documentation to call out these differences will save some of the head scratching.

I'm good now that you explained it so changing it is up to you.

**Comment by vygr** [comment]
renamed to (merge-obj) as that is actually what it does.
