### ISSUE TITLE
Concept of Iterable (mixin?)

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#121]
To allow user data types to participate in iterative functions (i.e. `each`, `reduce`, `map`, etc.)

**Comment by vygr** [comment]
Frank on the new xmap style objects we can achieve mixins quite easily. 

Have a class/object defined for the mixin functionality and you just merge the properties into the object you want the feature in ?

You need to be certain mixins have carefully chosen property names but it should be fairly easy?

We can also do iterators with the reverse idea. Call a method that hands you back an object that knows how to iterate it ? Kind of buds off an object with methods for forward, backwards and etc ?

**Comment by FrankC01** [comment]
**frankc01**
One thing I saw right away with the new model is:
```lisp
(defq e0 (emap-kv :a 0 :b 1 :c 2))
(print e0) ; -> @class/hmap/vtable
```
I seems wrong to have to write a specific print method to extract. I do have a "pretty print" that I have to update but that is a hack....

**vygr[m]**
We have a choice. Have a print method on the hmap VP class or not. The repl just calls that to print an object. If we want easy print for env objects the we have to put up with functions that return an env being a little verbose to use on the raw repl command line. Or you have to (print (tolist e))...

**frankc01**
This kind of ties to the original intent of a mixin and maybe why VP classes are the better route. But that means various other built-ins have to be aware that the object of the argument may need to be 'asked' for standard interfaces for serializing to string, iterating (first, next, last?, etc.) to work with any iterative function. That would mean changes to lists and strings, but it (IMHO) is cleaner all around:

```lisp
(print "This is my map " (emap-kv :a 0 :b 1)) ; -> This is my map {:a 0 :b 1}
(each (#(prin "el" _ " " %0)) (xset-k 1 2 3 4)) ; -> el1 1 el2 2 el3 3 el4 4
```
Data collections should be considered as first class citizens as well, again ... opinion

**Comment by vygr** [comment]
This could go somewhere.
