### ISSUE TITLE
Proposed enhancement: Adding constant convention and/or defconstant

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#128]
defconstant is implemented in sbcl. There is variable name info, which can be retrieved to determine if a variable is constant, or keyword—since both are immutable.

I'm still ok with +var+ though.

**Comment by vygr** [comment]
Extra (bind-fun) behaviour for symbols beginning with + would work well for this. ! As with pre-binding of functions this would allow optional pre-binding of any symbols that starts with +. Symbols being an obvious one, and then we can remove most of the uses of (const xyz).

**Comment by vygr** [comment]
Pushed this enhancement to (bind-fun) and changed GUI app events to be pre-bound constants to ilustrate.
