### ISSUE TITLE
Drop use of `xtras` dictionary

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#129]
With more effort on the lite-weight cousin (properties) the need for this construct is becoming obsolete.

At the moment, only `argparse` uses dictionary and changing this won't be be trivial

**Comment by FrankC01** [comment]
When dropped, should `properties` become `dictionary`?

**Comment by vygr** [comment]
What do you think ? Both are your constructs, what your feeling ? I'd always go for the one thing vs two things if one of the two things will be redundant...

**Comment by FrankC01** [comment]
Currently, the `properties` is more lite-weight and will have all the semantics of a true dictionary so... `dictionary` is redundant at this time (I think there is one use left in `argparse`
