### ISSUE TITLE
Dynamic re-bindable vars

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#130]
```
(defq *out* stdout)

(defund faux-print (s)
  (write *out* s))

(defq my-out (string-stream ""))
(binding (*out* my-out) 
  (faux-print "this))

; And

(with-bindings (*out* my-out ...)
(defun foo (x y)
   (faux-print x)
   (faux-print y))

(defund bar (a z)
  (faux-print a)
  (faux-print z))
)
```

**Comment by vygr** [comment]
As per the IRC conversation .. An automatic lifted variable on reassignment. I can see the reasoning and usefulness of this.

**Comment by vygr** [comment]
Folks, join the IRC #ChrysaLisp@matirix.org to witness Frank schooling me on basic stuff ;)

**Comment by vygr** [comment]
Ok a question on this that's nagging me. 

Why is this any different to just using (defq *out* newval) in the new scope???

When that scope exists the old value will be restored?

What am I missing here ?

**Comment by vygr** [comment]
It looks like (binding) and (with-bindings) are just a macro or function similar to what (let) does ?

Run some code in a new lambda that you (defq *out* xyz)

Why is this different to (let) ?

**Comment by FrankC01** [comment]
Accepted answer to this question: https://stackoverflow.com/questions/1523240/let-vs-binding-in-clojure

**Comment by vygr** [comment]
So this does seams like `*var*` are global. That stackoverlow mentions they are in the global scope etc.

Seams that (binding) and (with-binding) are there to allow such vars to be rebound as (let) can't actually effect them...

Now that's not the case in ChrysaLisp (for good or bad..) (setq) and (set) can be used to rebind any vars no matter where they are, global or not.

Same with (let), your quite able to use (let ((*var* newval)) .....) and you get your code executed with *var* bound to the new value, and the old is restored on descope.

I mention this in the LISP.md doc file.... under the list of things I will be in hell for ;)

ChrysLisp does have separate bindings for each instance of a Lisp object, each has its own vars, but they do share the boot.inc shared environment at the root. This was a speed and optimisation experiment, that could be changed if we REALLY had a good reason. At the moment there are no shared data structures created in boot.inc, only function and macro defines.
