### ISSUE TITLE
Module Namespace

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#131]
If one isn't careful in choosing function and/or var naming across modules, libraries or the system they can experience unintended consequences:

```lisp
; Module A (a.lisp)
(defq foo 0)

; Module B (b.lisp)
(defq foo 1)

; Module C (c.lisp)
(import 'a.lisp)
(import 'b.lisp)

(print foo) ;n  => 1
```
```lisp
; Module C (c.lisp)
(import 'b.lisp)
(import 'a.lisp)

(print foo) ; => 0
```

In some cases this may desirable if a module is defining well known function alternatives. Otherwise a **_namespace_** notion would be neat

```lisp
; Module C (c.lisp)
(import 'b.lisp)
(import 'a.lisp)

(print foo)   ; => 0 ... if not qualified
(print a.foo) ; => 0 ... qualified
(print b.foo) ; => 1 ... qualified
```

**Comment by vygr** [comment]
Some thoughts....

0) Extend (import) macro to allow an option environment to import into...

```lisp
(defmacro-bind import (_ &optional e)
	;(import path [env])
	(if e
		`(unless (find-rev ,_ *file_includes*)
			(push *file_includes* ,_)
			(eval '(repl (file-stream ,_) ,_) ,e))
		`(unless (find-rev ,_ *file_includes*)
			(push *file_includes* ,_)
			(eval (repl (file-stream ,_) ,_)))))
```

1) create a named environment that inherits from the current one...

```lisp
(defq xtras ((# (env 10))))
```

2) Import lib into this new environment...

```lisp
(import 'lib/xtras/xtras.inc xtras)
```

3) Call functions via this new lib environment ....

```lisp
(eval '(odd? 11) xtras)
t
```

4) Maybe wrap this up in some neat way with a few helper functions/macros ?

**Comment by vygr** [comment]
I've pushed the change to `(import)` and added the raw print method to the list class so the imported functions show up nicely on a print of the private env.

**Comment by vygr** [comment]
Might be better to make (import) into a function too while we are at it ?

**Comment by FrankC01** [comment]
import x/y/z as foo)
(foo.function args...)

(from x/y/z import funcname as bar)
(bar args...) ; => equivalent to (x/y/z/funcname args ...)

; No import
(x/y/z/funcname args ...)
(a/b/c/otherfuncname args ...)

; This behaves like current state
(import x/y/z)

**Comment by vygr** [comment]
OK, on the IRC I commented about prefixing before seeing this comment ! Prefixing does have benefits over loading into a separate env, re macro use etc.

**Comment by vygr** [comment]
Copied over from IRC:

If we go for a prefixing system for (import) it's going to have to be pretty clever at parsing the imported file and figuring out what is a function and what is not.... it will have to transliterate the library itself to use the prefixes ??? And that a bit of an issue, sometimes you don't even no until running the code if the thing is a function or not !

Could we have some way you have to 'mark' things to transliterate ? Like all function names and macros, plus all places they are called in the code as functions ?

How about some system where the lib is pulled into a separate environment to isolate it as I did above, but functions and macros 'marked' as `(exported)` get transliterated into prefixed call in the current environment ? Mmmm, this approach wins on a lot of levels on first go round my brain...

I this case the `(export)`d parts of the lib are turned into 'stubs' in the current environment that know how to call over to the isolated env. This would let macros work as well and mean we did not have to solve some NP complete style halting problem to figure out what was and was not a function in the lib code.....

**Comment by vygr** [comment]
Some other random thoughts going round the brain on this...

So in the normal, none name spaced `(import)` the `(export ...)` macro would just be nothing special, just pass its body through to the REPL as normal. But in the name spaced case, we would define the `(export ...)` macro inside the isolated environment prior to importing the lib file into it, and have that macro creates stubs in the current environment as well as letting it through to the REPL...

All we need is an `(export)` macro that knows what our scheme is ?

Just rambling thoughts so far, needs some rigour applied to it.

**Comment by FrankC01** [comment]
Comment on import and export (slightly different semantics)
@vygr: I'm starting with the assumption that if you are doing a first load of an import you are doing so into the default environment (putting aside your recent add)

**_PoC 1_**
`(import 'lib/xtras/xtras.inc)`
So I was going down the line, to start with, that each include has it's own environment by default and then you map indirections into the default environment. But functions calling other functions in the same module are visible to itself implying that a 'environment context switch' occurs when calling functions. If the interpreter understands it is using indirection it can switch the environment context before invocation.
Because there is no namespace modifier on the import they can be used directly from the calling module e.g.
`(nil? 7)`

**_PoC 2_**
`(import 'lib/xtras/xtras.inc :as 'x)`
In this case each function is realized in the default environment as x.nil? etc.
`(x.nil? 7)`

**_PoC 3_**
`(from 'lib/xtras/xtras.inc import (nil? ...) :as 'x)`
Expose only limited functions

**_PoC 4_**
Combine the above with a :private qualifier on function declarations -OR- declare an `(export nil? ....)` in an included module to restrict which functions the import can even consider mapping, leaving all not declared in the export as, essentially, private methods

With that fundamental machinery in place (big lift, I know) other import controls open up.

Realize I've not dug deeper but the above I've somewhat emulated

**Comment by vygr** [comment]
Since we added (env-push) and (env-pop) we have the rudiments of a module system. I've adopted an (export) macro recently and used the combo to hide internal symbols and only expose the modules defined exported symbols to the outside world.

This could also lead on to an (import-as) function/macro....

**Comment by vygr** [comment]
```lisp
(env-push)
(import "lib/asm/csript")
(def (penv)
	'some_other_name cscript)
(env-pop)
```

And we are also able to do something like (import) into a transient env, then export all the symbols within the current (tolist (env)) with a prefix !

**Comment by vygr** [comment]
This is working very well, I'm closing this till we actually need the 'import as' extention.
