### ISSUE TITLE
Date library

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#133]
A date library which returns date in a list (s m h date month year week) an encode-date to provide a time string and a decode to return to the list. Are there any requests for this library?

- unix date strings
- encoding/decoding time
- [ ]  allow for negative times and dates (before Unix Epoch)

**Comment by nuclearfall** [comment]
I resubmitted the library. The whole thing was a mess.

**Comment by vygr** [comment]
Merged in now.
