### ISSUE TITLE
New wallpaper/logo

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#135]
The old wallpaper was initially designed for higher resolution, reads as out of focus, and generally doesn't stretch well. The logo is also a bit unrefined.

This is packed with an svg of a new wallpaper and logo with standard sizes in tga format. There is a real modern look and the logo scales incredibly well.

The rights for these images are transferred under previously mentioned conditions if they are accepted for use on the project.

![wp](https://i.postimg.cc/m2v7XQWt/parens-1920x1080.png)
![logo](https://i.postimg.cc/TPCzJ25Y/parens-logo.png)

[parens-wp.zip](https://github.com/vygr/ChrysaLisp/files/5176550/parens-wp.zip)

**Comment by vygr** [comment]
Like them :)

**Comment by nuclearfall** [comment]
Closign this, as the wallpaper is already an option provided.
