### ISSUE TITLE
`clib` - A ChrysaLisp library management service

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#151]
At face value, a `brew' like thing that can manage `lib/...` libraries, information meta data and perhaps updates vis-a-vis a network stream capability.

Also thinking that TUI/GUI can leverage `path` configuration information so `(import ...)` doesn't need the degree of verbosity.

@vygr , @nuclearfall  and others... input welcome! If we have the confidence I will setup a Project and start building requirements,  Stories or whatever your preferred methodology dogma prefers to call that which "informs us in the direction to go in"   ....

**Comment by FrankC01** [comment]
No interest at the moment

**Comment by paul-hammant** [comment]
#260 relates. Package manager should be able to acquire packages for a container.
