### ISSUE TITLE
Clock 'tick'

### ISSUE THREAD

**Issue by vygr** [vygr/ChrysaLisp#157]
Recent changes to use the dat lib have made the minute and hour hands 'tick' like the second hand !

Needs to be smooth motion for those hands.

**Comment by nuclearfall** [comment]
I'll take a look. The day of the week is off as well. It definitely needs some work. I moved the all of the logic for the analog clock into a single function in clock/app.lisp. That is a likely candidate.

**Comment by nuclearfall** [comment]
I've created a float-time function that fixes the issue for the analog-clock while still allowing for timezone offset. I believe I've really fixed the day of the week issue this time.

**Comment by vygr** [comment]
confirmed fixed.
