### ISSUE TITLE
vdu :color doesn't override window :color

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#167]
vdu doesn't have a working :color attribute that overrides the color of the window background in which the vdu is placed.

**Comment by vygr** [comment]
Correct. It currently has a fully transparent background, only those characters that exist on the grid get to draw and those should before long have the ability to have both paper and ink attributes.

When we get to syntax highlighting in the editor these attributes will be implamented.

For now you can use a 'backdrop' component to add a coloured backdrop with a style behind the vdu class if you wish. set its :color property etc.
