### ISSUE TITLE
Basic paint application

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#17]
To complete a first demo, Chrysa should have at least a few expected applications, i’d suggest building a painting application, something to the order of MS Paint.

That would include the saving/loading of files, which I don’t think any of the apps support at the moment.

**Comment by vygr** [comment]
Paint apps are close to my heart. Back in the day I created 'The Advanced Art Studio' by Rainbird for the Atari ST ! And currently my work at Promethean LTD has been creation of their latest Interactive Panel Whiteboard and Annotate applications that rolled out into schools this term !

So yeah, I'd like time to do a paint app too !!! :)

**Comment by vygr** [comment]
I'm going to start on a paint app shortly. I'm just about to do a new release for the Windows port. I've tidied up things and removed the old tutorial stuff, no insult intended, just it's a bit out of date now and lots of other demo code is around and better docs now.

You will have seen recently I've push worked on the canvas vector graphics anti-aliasing code ready to use in the paint app.

I've also got plans in the paint app to show off an idea based on cached vector graphic objects, so wanted to get everything ready for that.

**Comment by vygr** [comment]
Just pushed the start of a simple whiteboard drawing app.

More to come on this.

**Comment by neauoire** [comment]
YES! I'm glad :)

**Comment by vygr** [comment]
Sorry mate. Took me a while to get there. :)

**Comment by neauoire** [comment]
All good, it's better not to rush these things.

**Comment by vygr** [comment]
Added paper styles, layered canvases, radio button selections and fixed stroking acute angles.

**Comment by vygr** [comment]
Coming on ! Shape modes and math tools to come next.
<img width="579" alt="Screenshot 2020-04-12 at 14 26 52" src="https://user-images.githubusercontent.com/10252816/79069921-db6f5a00-7cc9-11ea-970f-7d1d9f025a0b.png">

**Comment by vygr** [comment]
Added basic shape drawing.

**Comment by vygr** [comment]
I know your initial request had load and save options. But that’s only going to happen once try e file system debate is settled. 

So do you think this issue is closed ?

If so you can close it.

**Comment by neauoire** [comment]
Just pulled and tested! Yes, this is more than enough and is a good base to iterate upon.
