### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#18]
I was just poking around Oberon Native and Genera, I’ve always had a crush on aliases type and pixel UIs. I was wondering if you’d be into helping me to build the Chrysa UI into the likes of these OS classics. I’m curious to know what that would entail, if disabling aliasing is something that can be done.

I think that could make Chrysa stand out. I’d love to hear your thoughts on that.

**Comment by vygr** [comment]
I agree with the old nostalgia look and feel desires. But it's not really something we will do.
