### ISSUE TITLE
Define GUI window size in ./run.sh

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#19]
It would be very helpful for dev if I could send a window size as a script parameter so it doesn’t always take the full screen on load.

**Comment by vygr** [comment]
Yes ! Definitely a good idea. Even better would be to get dynamic resizing working too !

For now if you need to change the values go into gui/gui/class and you will find SCREEN_WIDTH and HEIGHT. change those and in a ChrysaLisp terminal prompt type ‘make boot’

Then restart with ./run.sh and there you go.

I’ll try get this done soon but I’ve got a bug fix I’m doing on my pcb router project that’s a high priority. :)

—————-
Chris Hinsley

**Comment by vygr** [comment]
Latest updated moves the GUI task into Lisp land ! It can now startup whatever screen widget it desires to act as the screen, have whatever size it wants etc and could load settings if needed. It also can change the login app or bypass that for setups that want Kiosk style 'just run this app at this size' starups.

```lisp
(import "class/lisp.inc")
(import "sys/lisp.inc")
(import "gui/lisp.inc")

;screen widget
(def (defq screen (Backdrop)) :style 0 :color +argb_grey2+ :ink_color +argb_grey1+)
(view-dirty-all (view-change screen 0 0 1280 960))

;fire up the login app
(open-child "apps/login/app.lisp" kn_call_open)

;jump to gui compositor
((ffi _ "gui/gui/gui" 0) screen)
```
