### ISSUE TITLE
Random Access Files

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#198]
A random access file behaves like a large array of bytes stored in the file system. There is a kind of cursor, or index into the implied array, called the file pointer; input operations read bytes starting at the file pointer and advance the file pointer past the bytes read. If the random access file is created in read/write mode, then output operations are also available; output operations write bytes starting at the file pointer and advance the file pointer past the bytes written. Output operations that write past the current end of the implied array cause the array to be extended. File pointer location should be able to be controlled by functions that inform what the current position is or be repositioned.

**Comment by vygr** [comment]
Pushed addition of `(stream-seek stream offset pos)` per the lseek() spec. Enjoy.
