### ISSUE TITLE
Have you considered leveraging LLVM Intermediate Representation?

### ISSUE THREAD

**Issue by AforAnonymous** [vygr/ChrysaLisp#2]
[See title]

**Comment by vygr** [comment]
Yes, LLVM IR code would be a potential target  and I'm looking at doing WebAssembly as well with separate browser instances used as virtual CPUs.

**Comment by vygr** [comment]
I've got plans to do RISC V and MIPS backends as well.

**Comment by AforAnonymous** [comment]
If you'd target LLVM-IR, that'd already give you WebAssembly via @WebAssembly's s2wasm, @lowRISC has a rapidly progressing RISC V backend for LLVM, and if I don't quite misremember, LLVM already supports MIPS... :)

**Comment by vygr** [comment]
While I do consider LLVM IR as a viable target, probably for the purpose of creating a final boot image for an application, I would not consider it a replacement for the built in compiler/assembler. Each have different goals. LLVM is a superb toolchain, I'm not dissing it.

As a benchmark of how long it takes to get a new CPU supported, you can check back through the git logs, I think I started seriously looking at it Aarch64 one weekend and the next weekend was getting kit to test the result on. Had a couple of silly encoding bugs, but overall about a couple of weeks part time evening sessions.

I realise that my compiler and optimiser is rather crude and simple, it does no fancy register allocation and the optimiser again does only simple things it can do without a full liveness and use/def analysis. I've done these things in the past and decided that it's not what I'm trying to achieve this time.

I could use some of the speed I have to burn on some extra peep hole operations that would definitely improve the code, but I've been trying to spread my efforts over the entire code base as best I can.

Plenty of rough edges at the moment, but going in the right direction I hope.

Regards

Chris
