### ISSUE TITLE
What are CPMs files?

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#23]
I noticed that images were in the `cpm` format, is there a way to include JPGs into a project?

**Comment by vygr** [comment]
.cpm are compressed pixmap format. This is an old Taos format from back in 1990. It's simple RLE encoded pixel format. Take a look in class/canvas/cpm.vp for the loader routine. Simple header and then run length pixel data.

Reason I haven't done Jpeg or PNG is that the decoders for them would probably be quite large ! But if somebody wants to have a bash at doing a decoder for .png that didn't take up a huge amount of space we could add it to the supported 'canvas 'load types easy enough.

Last time I compiled a Jpeg decoder written in C it was huge !!!

**Comment by neauoire** [comment]
Just looked at cpm.vp, and that's above my expertise haha.
I'll keep that for later then.

**Comment by vygr** [comment]
I should write the save code sometime too. Maybe when the paint app needs it ;)

**Comment by vygr** [comment]
The .flm files are film files, they have a .cpm formatted first frame then RLE encoded difference frames following, and loop back to the first at the end of file reached.

I want to get round to do the decoder for those too ! :( And the exporter...

**Comment by vygr** [comment]
FLM decoder now done. So I'll close this ticket I left open for a reminder.

Saving .CPM and an .FLM recorder will come along with the basic paint app...
