### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#25]
I was wondering what you thought about adding a wallpaper, it could be its own app `apps/desktop/app.lisp`? I'm not a fan of desktop icons, but I definitely enjoy setting a background. This could tie into creating a logo for ChrysaLisp, and adding it to the default boot. I'd be happy to tackle the making of logo, if you can help me make an app that always stays at lowest zIndex.

**Comment by vygr** [comment]
I raised an issue about allowing custom view for the backdrop and 'live' backdrops.

**Comment by nuclearfall** [comment]
@neauoire Just an idea, because I was messing with this a bit myself. Using a pair of lambdas to form the folds of a Chrysalis might work out well.

**Comment by nuclearfall** [comment]
I think this issue can be closed. Eventually we'll want a dialog to change backgrounds on demand, but we do have both a logo and wallpaper now.

**Comment by neauoire** [comment]
I'm glad to hear :)

**Comment by vygr** [comment]
OK :)
