### ISSUE TITLE
Display scaling options?

### ISSUE THREAD

**Issue by joelewing** [vygr/ChrysaLisp#256]
I'm using a Retina display where everything is scaled at 2x. Is there a way that I can scale the environment 2x, or at least adjust the font size to where it might be more readable?

I'm enjoying the project so far!

**Comment by vygr** [comment]
Joel I think I missed your msg, so sorry!

I think the SDL layer has an option to apply scaling or your can adjust your MacBook to run with a scaled display. 

I have my MacBook running scaled on my Retina screen. 

You have font size setting at the ChrysaLisp level in the ‘apps/login/pupa.inc’ files. Look for the *env_xxxx_font* settings. You can change them for guest or override them in your own user login folder. 

Best regards 

Chris

—————-
Chris Hinsley

**Comment by vygr** [comment]
<img width="1353" alt="Screenshot 2021-02-18 at 18 59 58" src="https://user-images.githubusercontent.com/10252816/108407333-84a4ac00-721b-11eb-8b4e-8f678b185412.png">

**Comment by vygr** [comment]
If you create your own login, this file will get copied to your own personal folder. Then you can override the settings for the fonts as you desire.

**Comment by vygr** [comment]
If you need a quick answer to something join up with Element app to the #ChrysaLisp@matrix.org chat room. :)

**Comment by joelewing** [comment]
Thanks Chris, I'll take a look!
