### ISSUE TITLE
src/main.cpp:37:11: fatal error: 'SDL.h' file not found

### ISSUE THREAD

**Issue by paul-hammant** [vygr/ChrysaLisp#257]
[MacOS 11.2.3]

brew install sdl2 ... doesn't install headers. Not sure how to overcome that.

**Comment by vygr** [comment]
Paul, sorry for the delayed reply. Martyn Blyss aka Bananearwig dropped me the Make_Homebrew file as he used that method to build on his MacBook M1. I personally got the SDL Framework from the SDL website and placed it into the /Frameworks directory, but I don't think Martyns script is set up to do it that way and you do need to install via homebrew. I've put a shout out to Martyn to see if he can assist, I don't have Homebrew installed here...

**Comment by paul-hammant** [comment]
No unnecessary apologies Chris!

```
curl https://www.libsdl.org/release/SDL2-2.0.14.dmg -o sdl2.dmg
hdiutil attach -mountpoint /Volumes/sdl2 sdl2.dmg 
mkdir ~/Library/Frameworks/
cp /Volumes/sdl/SDL2.framework ~/Library/Frameworks/
```
Does it I think.

After .run.sh how do I launch more than one apps/clock at a time?  With TaOS, back in the day, there was a tumbling cube demo that didn't stammer if you dragged one over another ... unlike all other windowing OS's at the time.

**Comment by vygr** [comment]
Yes we probably need a terminal command app to launch a GUI app. ! I used to run a command line to launch like hundreds of clocks or such to show the GUI just did not slow down. Compositor demo. 

Ok I will think on adding a ‘run ...’ command app. Then we can do that demo again. 

For now just keep running Boings and so forth from the launcher till your click finger gets numb. It won’t slow down. And after hundreds of them running you have the joy to run a few Raymarch and a full OS build in a gui terminal and still get under a second for a build :)

—————-
Chris Hinsley

**Comment by BananaEarwig** [comment]
Apologies for arriving late. Paul are you all set now?

**Comment by paul-hammant** [comment]
My bad - the launcher is what I was looking for. Maybe something in the README suggesting the user should click on the desktop to see the launcher.

I also tries this in the Terminal ->

```
../apps/boing/app
```

And it just hangs. Small issue, I bet.
