### ISSUE TITLE
Package manager needed

### ISSUE THREAD

**Issue by paul-hammant** [vygr/ChrysaLisp#258]
Nix, apt-get, pub.dev, cpan, maven-central .. there's many to be inspired by.

Reproducibility, whatever that means for this flavor of lisp, should be a consideration if the distributable piece is binary.

**Comment by vygr** [comment]
@FrankC01 also has some thoughts on these issues !

**Comment by FrankC01** [comment]
@paul-hammant I re-opened https://github.com/vygr/ChrysaLisp/issues/151 which was the original enhancement/discussion but no-one seemed to be biting

**Comment by paul-hammant** [comment]
Lets reconvene on #151
