### ISSUE TITLE
Interprocess communication port needed

### ISSUE THREAD

**Issue by paul-hammant** [vygr/ChrysaLisp#261]
The Amiga's ARexx allows processes to chat to each other from the late 80's onwards. At some level that stuff was more capable than AppleScript and alternates today (30 years later).  NetRexx lost critical features. ObjectRexx was something different.

This wasn't a unix-ethos pipe/socket way of working, it was a proper programming linkage. Judged by 2021 standards it probably had hundreds of eval() style security shortcomings.

Clearly for  ChrysaLisp, this would be a lisp grammar.  @jasonhansel started something some time back - https://github.com/jasonhansel/functional-rexx/blob/master/functional.rex - but didn't get too far.

**Comment by vygr** [comment]
@FrankC01 has been working on a standard IPC and comms lib that is higher level than the basic message system!

Check out the 'lib/ipc/' folder and Franks examples. 

This ties into other work Frank has done on de/serialisation of data structures and classes to and from message buffers !

Worth a look over and a chat with Frank.

**Comment by paul-hammant** [comment]
Sounds great, and way further ahead than I imagined. Great work @FrankC01.  I found an old ARexx manual - https://issuu.com/ivanguidomartucci/docs/amiga-programmers-guide-to-arexx---ebook-eng - yanked back!!

**Comment by vygr** [comment]
Well Frank when off to do Crypto mining... after building a kitchen :)

**Comment by vygr** [comment]
I'm still having an issue with this PR. I don't really get it.

We have this already, don't we. ?
