### ISSUE TITLE
reload definitions in lisp

### ISSUE THREAD

**Issue by TheFausap** [vygr/ChrysaLisp#265]
Hello,

I wrote some functions in an .inc file and I am able to load it with the import command in a lisp session.
The problem is, if I modify something in the existing functions or add some new defun in the inc file, even if I run the import command again, the new added defun or the changes are not loaded in the existing lisp session.
I have to exit from lisp and run it again. So i can import the new modified inc file.

Is this an expected behavior?

thanks,
Fausto

**Comment by vygr** [comment]
Can I confirm what went wrong?

I must admit I don't tend to re import files. The issue here is that import, check in boot.inc, keeps a list of what files have been imported already.

So re importing will think you all ready did.

Does this sound like the issue ?

Regards 

Chris

**Comment by TheFausap** [comment]
Exactly :)
There's no problem, for me, exiting lisp and opening it again. I opened the
issue because I didn't know if this was expected or not.

**Comment by vygr** [comment]
Sorry it took 22 hours to notice this post :(

If you want fairly instant feedback on questions join us over on #ChysaLisp-OS:matrix.org I highly recommend the Element app from element.io as the reader.

Chris
