### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Ashis231** [vygr/ChrysaLisp#266]
When I try to compile it using `make`

it throws the error `cannot initialize a parameter of type char * an lvalue of type void *`

**Comment by Ashis231** [comment]
machine: x86-64 Ubuntu 18.04
compiler: clang
libsdl2: yes
libsdl2-ttf: yes
extracted snapshot: yes

**Comment by vygr** [comment]
I havn't noticed this on my Ubuntu build. Does it just require a cast ? What line was the error ?

**Comment by vygr** [comment]
This should be fixed now.
