### ISSUE TITLE
rather a request: RISCV would be great

### ISSUE THREAD

**Issue by enthusi** [vygr/ChrysaLisp#269]
It would be very nice to see this ported to RV64 as well.
The major work appears to be 'in' arm64.inc related to arch, I guess?
Very fresh project in total. Thank you!

**Comment by vygr** [comment]
Just pushed the start of the work. 

And yes arm64 is a good chunk of the work. 

But I've started at the vp64 stage as that lets us test a few things before we start on the riscv64 emit file.

Shake up the Makefile, get the build functions being a bit more DRY etc.

**Comment by vygr** [comment]
Now building 5 platforms in under 5 seconds on my old MacBook. 

I'm so jealous of those M1 Ultra owners :)

**Comment by enthusi** [comment]
Hehe. Amazing work! Pulling it on the VisionFive2 (rc64) right now. Happy to test...

**Comment by vygr** [comment]
I have a Riscv64 dev board arriving from China via a patron. ;)

I'm looking at getting an QEMU environment going on my MacBook but so far it not working out. :(

Still I can do a lot blind if needed.

If you have a Riscv64 Linux going that would be a great help for testing things.

Could I encourage you to joint the chat room on Element ? We don't bite, just take the Pisa a lot :)

**Comment by vygr** [comment]
https://matrix.to/#/#ChrysaLisp-OS:matrix.org

W are already debating if you know a curry recipe we don't already have....

**Comment by vygr** [comment]
![telegram-cloud-photo-size-4-5947450423084431598-y](https://user-images.githubusercontent.com/10252816/214596714-42625dda-834f-4493-aefa-f961e0954217.jpg)

**Comment by vygr** [comment]
Thanks you for testing this. A lot of happy folks over here :)

**Comment by vygr** [comment]
Major thanks on helping to bring this platform up with us.

Printf debugging for the win indeed :)

**Comment by vygr** [comment]
I think with the new release we can close this ticket :)
