### ISSUE TITLE
backdrop app ?

### ISSUE THREAD

**Issue by vygr** [vygr/ChrysaLisp#27]
GUI process currently uses a black label as the screen widget. Should at least be able to specify any view class, and would be very nice if could run a live application to supply the view.

Should be possible to have a live backdrop like Boing running etc

**Comment by neauoire** [comment]
Here's some ideas, I currently use Ubersicht on OSX, it allows me to add the output of shell scripts to the desktop(see top bar), I use it to display the time, emus, network, memory, cpu, battery. I can imagine a system for Chrysa that is as flexible.

<img width="1280" alt="screen shot 2018-10-07 at 7 09 57 am" src="https://user-images.githubusercontent.com/1455726/46574951-37379380-ca00-11e8-8481-26519ddf3598.png">

**Comment by vygr** [comment]
Added a backdrop app and support for apps living in the background!
