### ISSUE TITLE
Bootstrapping ChrysaLisp on ChrysaLisp?

### ISSUE THREAD

**Issue by vitiral** [vygr/ChrysaLisp#279]
Hey, really like the project. I have a quick question: can you currently bootstrap ChrysaLisp on ChrysaLisp? By this I mean can you be running a ChrysaLisp operating system and develop and build a new ChrysaLisp OS from scratch (from only source code, no binary blobs)?

If not, is such a thing on the roadmap?

My other question is: what is the language which handles "native" code? I don't see any C or assembly files in kernel directories or elsewhere. Are these `.inc` files somehow being compiled into native code?

Thanks for your time and the great project!

**Comment by vygr** [comment]
We kind of do bootstrap ChrysaLisp on ChrysaLisp. What I mean by this is that the boot_image in the snapshot.zip is actually a binary for the VP64 EMU ISA. At install time we use this to run a 'real' `make all boot` which then creates the native version of the system for your platform.

Damb, it took me a while to see this, my apologies for the late reply.

Hop onto the Element chat room to get instant feedback on questions etc.

Chris

**Comment by vygr** [comment]
The platform isolation files are in the `/src/host/` folder BTW, this defines the callback to host OS table for the functions we currently go back to the host OS for.

**Comment by vygr** [comment]
Join us at #ChrysaLisp-OS:matrix.org for banter. https://element.io/ recommended.

**Comment by vitiral** [comment]
I assume that's an IRC channel? I don't understand how going to element.io will help, when I try to find how to join a chat there all I see in "get started" is [sales](https://element.io/get-started).

I've created the Civboot.org project, which I feel _may_ have a few goals in common with ChrysaLisp. My current project is 

* Write a lua compiler in lua: generate lua bytecode from lua syntax using only Lua
* Write something like an assembler in lua [1] (that can link to C functions/etc)
* Write an ultra-simple lua execution kernel in both C and the assembler [2]. Note: ignore the bits about "stack Lua", I think I'm just going to target the normal Lua VM.
* From this, lua will be self-bootstrapable (minus syscalls/etc -- that would require writing a lua-driven OS in the assembler which might be the next step!)

Obviously this is _different_ from ChrysaLisp, but I also thought y'all might be interested in the project as a bootstrap point for ChrsaLisp. In addition, I've wrote some [pretty][metaty] [neat][pegl] libraries and [apps] which are general-purpose and it would be great to collaborate.

[1]: https://github.com/civboot/civboot/blob/main/blog/0013-civboot-languages.md#spasm-structured-portable-assembly
[2]: https://github.com/civboot/civboot/blob/main/blog/0013-civboot-languages.md
[pretty]: https://github.com/civboot/civlua/tree/main/metaty
[neat]: https://github.com/civboot/civlua/tree/main/shim
[apps]: https://github.com/civboot/civlua/tree/main/ff

**Comment by vitiral** [comment]
Also, can I say how much I appreciate the confirmation here:

> Don't get the idea that due to being coded in interpreted Lisp the assembler and compiler will be slow. A fully cleaned system build from source, including creation of a full recursive pre-bound boot image file, takes on the order of 2 seconds on a 2014 MacBook Pro ! Dev cycle (make) and (remake) under 0.5 seconds. It ain't slow !

As long as I keep my big-O's small for the workloads I'm doing, performance won't be the problem! So much of the bloat in build times is due to the bloat in software. The myth that everything needs to be optimized is because even developer tools have been wrapped in 20 layers of indirection.

**Comment by vygr** [comment]
Glad your going through the docs.

The Element chat room is worth joining if you can. 

unfortunately my sister was taken into hospital yesterday with a heart attack. So my attention is a bit elsewhere at the moment.

Other people can help you in the chat room though.

**Comment by vygr** [comment]
![image](https://github.com/vygr/ChrysaLisp/assets/10252816/de5113c1-0406-4623-99e6-c898d91f53ef)

**Comment by vygr** [comment]
https://element.io/

**Comment by vitiral** [comment]
Please take care of your sister. 

I figured out how to join the Chat btw, you have to click "Sign In -> Create Account", not "Get Started"

Or you could just give this link and I think it would make it easier for folks to signup

https://app.element.io/#/room/#ChrysaLisp-OS:matrix.org
