### ISSUE TITLE
Global windows controls

### ISSUE THREAD

**Issue by neauoire** [vygr/ChrysaLisp#28]
I was wondering if you we could start building windows management shortcuts.
I would love it if we could use `win/cmd + key` to control maximize, minimize, hide, stick to left, etc..
What do you think?

**Comment by vygr** [comment]
Needs to be added yes. But then the whole keyboard focused UI elements system is yet to be completed. Currently the GUI process just directs key events to the UI element directly under the cursor, now that's not even 'focus follows mouse' as that scheme targets the window under the mouse and maintains a focused element within that window !

So what's currently done is far too crude. What I did last time round, in another life, was to have a keyboard input token (one of many such input tokens, joystick etc) and the UI element that owned the token got the key events. Then layered on that was a system for token traversal with the arrow keys in and out and across containers, with scrollable regions responding automatically to keyboard token setting events and making the receiving UI component visible etc.

I'd probably go for the same idea again as it was very flexible and allowed containers like Flow and Grid to take most of the heavy lifting away from the application logic.

Another job on the TODO list !

**Comment by vygr** [comment]
We are moving towards an actions bound to key strokes and events system in the latest apps. This now has +/- for windows max and min and we can easily add more standard actions. Eventually these actions may be scriptable in the way Apple automator does...
