### ISSUE TITLE
Take some Inspiration from the Burroughs Large Systems Group Master Control Program?

### ISSUE THREAD

**Issue by no-identd** [vygr/ChrysaLisp#38]
https://en.wikipedia.org/wiki/Burroughs_MCP

Incredible file system design for one thing.

**Comment by vygr** [comment]
I'll do some reading !

**Comment by no-identd** [comment]
Speaking of file systems:

http://css.csail.mit.edu/fscq/

(made by @mit-pdos)

**Comment by nuclearfall** [comment]
As another file system idea, a git based implementation would be purely functional. Something along the lines of this project [https://github.com/presslabs/gitfs](https://github.com/presslabs/gitfs). 

The opportunity to change how we look at file systems here is huge. A git based filesystem could allow diff'ing user data. This would effectively give the timeline of Pages or Numbers on a Mac.

Git is a tried and true management system that is purely functional in nature.

**Comment by no-identd** [comment]
I'd strongly prefer something pijul based over something git based, as it'd have even stronger guarantees.

**Comment by vygr** [comment]
No. I'd watch Tron and vote against this.
