### ISSUE TITLE
Use sprites for graphics, from the ground up?

### ISSUE THREAD

**Issue by no-identd** [vygr/ChrysaLisp#39]
See here:

http://alvyray.com/Sprite/

Albeit—and I don't think that that makes for much of a caveat—I do think the concept of sprites presented there could do with a move from [rectilinear polygons](https://en.wikipedia.org/wiki/Rectilinear_polygon) to some (further) generalization of [isothetic polygons](https://en.wikipedia.org/wiki/Isothetic_polygon) which could represent any [planigon](https://en.wikipedia.org/wiki/Planigon)

(I do suspect that such a generalization likely already exists somewhere in the literature, whose name—and hence literature on it!—I have yet to find. The Wikipedia page for rectilinear polygons—but not the one for isothetic ones!—points to two generalizations, but neither of them seems particularly helpful for representing e.g. a regular hexagon…)

**Comment by vygr** [comment]
That looks like a very interesting paper !!! I will definitely give this a look over. Thanks for the link.

**Comment by vygr** [comment]
Sorry for taking a while to get back on this.

So, I read the paper, and very interesting it was. But it didn't really push me in a different direction to how I currently do the compositor. Let me explain...

The paper talks about the invention of alpha and specifically the pre-multiplied alpha and how this benefits so many things. Totally agree, the canvas stuff in ChrysaLisp has always been pre-mul alpha for exactly these reasons. The paper also deals with the idea of a box algebra, but I didn't see a conclusion to these things in the paper... am I correct that this paper never got finished ? Forgive me if I missed Alvy's death or such.

The GUI (gui/region/*) code does all the box (rect) algebra for the compositor. This is used by the GUI update function (gui/gui/update) to build a set of contexts for every exposed (visible) dirty region on the screen and then calls down to GUI components draw methods to fill in the exposed region in the correct sequence. Typically the draw function ends up using some pre-multiplied-alpha resource (font glyph cache, canvas bitmap from the GPU or some fairly boring GPU box fill/alpha fill.

I do believe that what I'm doing is in the spirit of the paper. Many years of trying to get an underpowered home computer to meet the frame blank period, and get its sprites drawn, does that to one ;)

I've not yet moved to interfacing direct with the GPU for polygon drawing ! That will probably influence how I go forward with the (gui/ctx) API. At the moment it's extremely spartan, having about 5 methods in total.

And I'm not ruling out that I may have missed something monumental in the paper, but just too weak minded to see it. :) I am a bear of very little brain when it comes to math :(

Chris
