### ISSUE TITLE
suggestion for DHT object store

### ISSUE THREAD

**Issue by tidux** [vygr/ChrysaLisp#4]
Check out https://github.com/ipfs and its various implementations.  The protocol's still a work in progress, but it provides checksum-addressed object storage and runs over all kinds of network transports.  I've used the https://github.com/ipfs/go-ipfs implementation for huge file transfers over WAN with great success.

**Comment by vygr** [comment]
Yes, I was looking at IPFS a while back. Very interested in the ideas there. :)

Chris
