### ISSUE TITLE
Sort order incorrect

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#45]
from TUI or Terminal:

`sort 4 5 7 100`

100 will be first in the list.

**Comment by vygr** [comment]
Sort cmd app is doing a text based sort ! Not numeric. 

Chris

**Comment by vygr** [comment]
If you look at the last line in the cmd/sort.lisp file you will see it sorting with the ‘cmp’ function. That args are text strings and cmp is a text compare function. 

Chris
