### ISSUE TITLE
Logo for ChrysaLisp

### ISSUE THREAD

**Issue by nuclearfall** [vygr/ChrysaLisp#46]
Branding can be an important part of attracting developers. The ability to add wallpaper would also help. I've designed a logo for the OS. Feel free to use it, make suggestions, or decide it's not what you're looking for. 

I don't know if this is helpful at all: https://github.com/Ramarren/png-read

![ChrysaLisp v 0 6 512px](https://user-images.githubusercontent.com/41907342/70392634-a368ab00-19a7-11ea-8d0c-f76dd43e594a.png)
[Logo.zip](https://github.com/vygr/ChrysaLisp/files/3936571/Logo.zip)

**Comment by vygr** [comment]
Personally I like it :) as soon as I looked at it I got a good feeling from it :)

What do others think ? Anybody looking at this thread ?

**Comment by nuclearfall** [comment]
Thanks!

I really love logo design. Also, theming is fun for me. So, if at some point you're able to make windows themeable I can do some window decoration.

**Comment by vygr** [comment]
Can you post the other variant to have a look at ?

**Comment by vygr** [comment]
What would be best is an SVG version, and to convert that over to ChrysLisp vector graphic commands ! So it could be rendered at any size etc, like the clock demo.

This might be a good time to think about working on some SVG importer !

**Comment by nuclearfall** [comment]
That would be really good.

**Comment by nuclearfall** [comment]
![ChrysaLisp v 07 256](https://user-images.githubusercontent.com/41907342/70439990-cb631780-1a56-11ea-916f-a5049571ef48.png)
[ChrysaLispv0.n+1.zip](https://github.com/vygr/ChrysaLisp/files/3939905/ChrysaLispv0.n%2B1.zip)

Here's the other version. Both have zip files attached with 512.png and svg graphics.

**Comment by vygr** [comment]
I like the second one best ! Something about the butterfly leaving the circle appeals to me. :)

I converted the 2 versions to .tga and added a quick .tga import routine to the system. Updated just now, so people can admire your design.

**Comment by vygr** [comment]
Looking at the .svg files they contain embedded .png data ? They are not just svg path drawing commands ?

**Comment by nuclearfall** [comment]
Ahh, sorry. A color adjustment on a layer. I'll re-export.

**Comment by nuclearfall** [comment]
This one should be clean.
[ChrysaLisp v.0.8.svg.zip](https://github.com/vygr/ChrysaLisp/files/3942578/ChrysaLisp.v.0.8.svg.zip)

**Comment by vygr** [comment]
Thanks, it will take a while to get the svg import going, but I now have something to work with ! In the mean time I have add the .cpm file saving and conversion tool, tocpm. I'm getting about 54KB for the logo file now. So not too bad for a cheap rle pixel format.

**Comment by nuclearfall** [comment]
Not entirely sure what I think about this wallpaper. It maybe a little chrometastic, and I can't seem to get it to convert using tocpm. Not sure if there is extra junk attached. But when I get frustrated/tired coding in a new language I generally take some time to work on design elements.

I've done a little experimentation with trying to get clickable images, and I'm thinking about a backdrop with a canvas on it. Eventually, I might find a way to make an icon dock launcher. I'll fiddle with, but it's obviously not high priority stuff.

[ChrysaLisp640x480.tga.zip](https://github.com/vygr/ChrysaLisp/files/3963260/ChrysaLisp640x480.tga.zip)

**Comment by vygr** [comment]
Hold on the wallpaper for now, I was going to look into getting the host GUI window resizable and that will probably change how I do the background !

The TGA file may be a type 2 TGA and the quick and dirty TGA importer I did was a type 1 header, 32bit only. So I will look at the file and see if that's the case.

Label and button already use a flow view ready to take the addition of images to go along with the text ! And I was thinking the same thing that I should enable a method for allow the addition of a canvas to this flow, then we can have the usual suspect of image and text flowed how we want for image buttons and dock buttons etc

I was thinking yesterday that having an icon.cmp file in each app folder to show in the dock/launcher would be a plan. So we are both thinking about this at the same time :)

**Comment by vygr** [comment]
I used this online TGA convertor to produce the TGA's from your logo PNG files, that produced a TGA header that was fine with the tocpm convertor.

https://image.online-convert.com/convert-to-tga

**Comment by vygr** [comment]
I like the wallpaper image though :)

To properly support a decent wallpaper we should extend the canvas view to have a few more features, ability to specify alignment, centering, stretched drawing with or without aspect correction etc

Then a wallpaper would just be a image loaded into a canvas view that was set as the backdrop object. That is on the TODO list here as well. !

**Comment by vygr** [comment]
Just pushed a fix for the 24bit TGA loading, 8bit grey .cpm saving. And added your new test images to the image app.

**Comment by TheMartynBliss** [comment]
Looks good!

**Comment by nuclearfall** [comment]
My only concern was that the pallet is similar to Mints.

**Comment by nuclearfall** [comment]
Did you want to remove the background circle so it matches the logo on the wallpaper? Either way, we should be able to close this afterwards.

**Comment by vygr** [comment]
As a log rather than wallpaper, I quite like the circle ? Maybe it should be the blue color like the wallpaper though ?

**Comment by nuclearfall** [comment]
I've been thinking t about an icon that can easily be scaled from very small to very large. I've come up with something that I think captures the essence of the original logo, while still being easily recognizable as a very small scale either colored or in monochrome. 

Parens with an upside down lambda form the butterfly. You'll notice there's no _tail_ recursion ;)

![ChrysaLisp-96](https://user-images.githubusercontent.com/41907342/74452144-475a5100-4e46-11ea-9c68-0a0744f28f43.png)
For a taskbar or such:
![ChrysaLisp-16](https://user-images.githubusercontent.com/41907342/74452247-6fe24b00-4e46-11ea-81c1-8f6627998347.png)
What do you think?

**Comment by vygr** [comment]
Quite like the design !

**Comment by nuclearfall** [comment]
So, what I think I'll do is pack this up with raster images for typical sizes and an svg, and then call this one close, if you think that will work.

**Comment by vygr** [comment]
Yes. Definitely keep the svg as eventually we will have the ability to render those.

**Comment by vygr** [comment]
Closing this issue now as we are already way beyond the first rev of the logo ;) Thanks Gary.
