### ISSUE TITLE
Advanced Debugging Features?

### ISSUE THREAD

**Issue by no-identd** [vygr/ChrysaLisp#5]
You might wish to consider implementing advanced debugging features, like Medic:

* https://github.com/lixiangqi/medic
* https://docs.racket-lang.org/medic/index.html
* https://www.cs.utah.edu/plt/publications/fpw15-lf.pdf
* https://www.youtube.com/playlist?list=PL_U7i0VKF_mh7Vh3o2YyteoTL1tErHY64

And Ripple (for which unfortunately I have yet to find source code, and which one must distinguish from @ripple, with which it has, to my knowledge, zero relation):
* https://dl.acm.org/citation.cfm?id=3136019
* https://www.youtube.com/playlist?list=PL_U7i0VKF_mjF_SMiPbz-P_vUkNGHHjm8

Both of the above made by @lixiangqi & @mflatt. 🙂

P.S.:
Only semi-related to the above, here's a semi-related paper from December that might interest y'all: https://hal.inria.fr/hal-01662336/document

**Comment by vygr** [comment]
That's interesting, thank you.

Chris

**Comment by vygr** [comment]
I've just added a Debug app as part of the new System Services implementation.

Now, this isn't the be all and end all of debugging, but I'm heading towards the auto instrumented debugging you pointed me at a few months back ! See I do get round to things eventually ;)

Debug statements go to, if it's running, the DEBUG_SERVICE, and currently I've got a Lisp GUI app that registers itself as such. This then can control the stepping of debug statements in the code at a VP or Lisp level.

So the next step would be to do an auto instrument decorator macro, or such, that adds the debug statements to the code without needing to do it manually.

But already this is a great addition. Being able to watch thousands of spawned threads do their thing and step them etc is a great leap forward.

Chris

**Comment by vygr** [comment]
You might have noticed that I detoured to do a C++ Clang/LLVM version of the Lisp to get a real feel for what the difference was compared to my own crude roll your own compiler.

I need to update that now with the recent change to write-char so it can build the system again, but in the STATUS.md file I show the results so far. While I could put more effort into trying to squeeze more performance out of the C++/LLVM version I have tried to stick to the same game plan as I do for the Native Lisp. Not very encouraging results from LLVM here so far on performance or footprint.

I'm not having a go at C++/LLVM I think they are both wonderful things, but they are not going to match what ChrysaLisp native is doing. And I still don't consider my optimizer up with the best. C++ is my go to language when doing work outside ChrysaLisp dev. Have to wait for ChrysaLisp to take over the world before that situation changes :)

Regards

Chris

**Comment by vygr** [comment]
I refer folks to the recent chat room debate about how we could add a scroll back history to the runtime.

**Comment by vygr** [comment]
Does the ability to think clearly count ?

**Comment by no-identd** [comment]
> Does the ability to think clearly count ?

wdym/hdym?

**Comment by vygr** [comment]
We now have debug instruments for stack frames, profiling and network wide statement tracking.

**Comment by vygr** [comment]
Are we not there yet ???

You can take the debug and profile code and add any instrumentation you desire.

I really don't see how we can offer anything more powerful than that.

**Comment by vygr** [comment]
On that I'll close this pr as it's going to become some argument about UI presentation and option boxes.
