### ISSUE TITLE
Running on embedded hardware

### ISSUE THREAD

**Issue by octetta** [vygr/ChrysaLisp#55]
Apologies if I'm way too far in left field on this issue. Love all the care, thought, and work going into this.
Any hopes this code base could offer some of the promises of the Tao system of lore, specifically related to pushing code to tiny/networked hardware that isn't 64-bit (8-bit Arduino/AVR)?
Maybe that's too small a target, but how about something like an ARM Cortex-M0?
What do you think the smallest target is reasonable for this project?

**Comment by vygr** [comment]
I had a very hard time deciding to go 64bit for the VP vm this time, but in the end that's the choice I made. I wanted to take future directions in mind and the trend is towards 64bit. Even SOC FPGAs for IOT are now coming with Dual and Quad core 64bit ARM.

It's always possible to do a 32bit or lower version but it's going to suffer a lot of performance drawbacks, plus it would bulk up the VP ops if I was to specify 32bit ALU operations as well as 64bit.

So for now, and possibly forever (but never say never), it's going to be 64bit wide register devices only.

Regards

Chris

**Comment by octetta** [comment]
I respect that. Indeed another project I follow (Inferno/Limbo) looks like it's stuck forever at 32-bit. I suspect I'd be better served by assisting this project with mailbox interface (?) or 9P (?) to the little devices. Pharo (a port of Squeak Smalltalk) has taken a similar approach via "Firmata" which is a curious re-imagining of the MIDI protocol.
