### ISSUE TITLE
`(get ...)` error: symbol not found

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#76]
In both the Lisp repl as well as in lisp program/script

**Comment by vygr** [comment]
Get is a macro in the gui/lisp.inc file. Doesn't get included by boot.inc.

;some helpful macros
(defmacro get (_ b)
	;(get env form) -> val
	`(eval ,b ,_))

We could move it to boot.inc if you feel it's general enough to go in there ? Or you can just use (eval) directly.

**Comment by vygr** [comment]
I've promoted it to boot.inc as I feel although it's only doing an (eval) I like that it hides that and gives something that feels like a counterpart to set/def.

If your happy with that feel free to close the ticket.

**Comment by FrankC01** [comment]
So, here is the test:

```
(def: '(x y z) (env))
(get (env) x) ; => x
```

Works like a charm!
