### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#79]
This is causing a segmentation fault:

`(reduce (lambda (acc el) (cat acc el)) '(fee fie foe fum) (list))`

Before getting to this simple reproduction, I was seeing `Malloc fail !!!funcs.sh: line 60:`

**Comment by vygr** [comment]
Been busy with work stuff this week. But over this weekend I’ll catch up !

Thanks Frank

**Comment by vygr** [comment]
Pushed a fix Frank. Make sure to rebuild your image with “make boot”

Should now correctly throw an error. 

Well spotted !

**Comment by FrankC01** [comment]
Hmmm, so now `cat` function is not like standard lisp `append` so
```
(defq p1 (list 1 2 3))
(cat p1 4) ; => Syntax error
```
I know I can use `push` but curious...

**Comment by FrankC01** [comment]
So `cat` was the culprit. All good
