### ISSUE TITLE
`docstrings` equivalent

### ISSUE THREAD

**Issue by traverseda** [vygr/ChrysaLisp#8]
In the interest of having good documentation, it would be nice if objects were self-describing in some way. I don't really do lisp, I work with python, but my understanding is that in lisp objects an implement a "describe", "inspect", or "documentation" method?

To get such a system integrated with sphinx (for auto-generating object documentation), we'd need a way to get that information *out* of ChrysaLisp, presumably a command that output all the documentation in a semi-structured way. Sphinx already has support for common lisp, and if we think that would work on chrysa-lisp I could try setting that up, but I think it would require that the code could actually run under common lisp.

I might be able to just set ChrysaLisp as the lisp executable for sphinx to use, but I don't know if that would work or not.

**Comment by traverseda** [comment]
Awesome, feel free to let me know if you need any changes to the sphinx side of things.

**Comment by vygr** [comment]
If I can get some REF.md file auto created containing the current functions info, I'll add support for a description.

Probably a (make-doc) command. Anyways, job for tomorrow :)

**Comment by vygr** [comment]
First attempt at an (make-doc) command pushed :)
Needs work, but gets us started.

**Comment by traverseda** [comment]
I'm not sure how to run that from the linux environment.

**Comment by vygr** [comment]
Run the text ui. Via './run_tui.sh' then at the terminal prompt, type 'lisp.lisp' to run the Lisp interpreter. Then you can run (make-doc) to generate the doc/CLASSES.md file from the sources.

cntrl-c to exit the Lisp terminal.

The (make-doc) function is in the 'cmd/asm.inc' file at the bottom if you feel like having a play with the code. It's reasonably easy to follow.

Regards

Chris

**Comment by vygr** [comment]
Not exactly 'docstrings' but the result is good. Thanks for the prompt to get this done Alex.

Chris
