### ISSUE TITLE
Shell commands and pathing

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#82]
Currently the Terminal application assumes that a command entered can be resolved in the `cmd/` folder.

It would be desirable to be able to enter a command at the shell prompt and have the terminal app search through a configured 'path' to resolve the location of the command location and load from there unless the user has provided a qualified command.

For example, assuming Terminal preloaded a configuration file upon startup from `config/shell.profile` (or similar) containing:

```
export PATH=cmd/:examples/  ; Search order is important
export ENV_VAR1=blah 
``` 
The export declaration semantics are that PATH and ENV_VAR1 are automagically added to the environment.

Upon Terminal startup it reads and processes the profile and, with the configuration of PATH, can do a search through the locations to resolve the request. (Is the environment ready this early?)

Alternately the user can specify an absolute path at the command

**Comment by vygr** [comment]
yes, we could have a *env_path* for each user login, like the other user *env_xxx* things, no problem. And try match those commands for the TAB completion.

Sure.

**Comment by FrankC01** [comment]
Also, the up arrow in the TUI shell does not recall last. I'll start with just getting a qualified name optional at the command line and forego the decoration of `cmd/` & `.lisp`. Then find where you are doing the environment thing.

**Comment by vygr** [comment]
The TUI is much more of a helper than fully functioning equivalent of the GUI terminal. 

I’d like to see them more unified but this would involve some extra work in the platform specific side of the main.c with regards to echo or raw modes for the host shell. Not always an easily portable API to call especially on Windows:(

**Comment by FrankC01** [comment]
`lib/clenv/clenv.inc` and `apps/terminal/tui2.lisp` provides enhanced shell functionality
