### ISSUE TITLE
File Delete

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#93]
The ability to delete files. Will require changes to `main.c` and a bubbling up of the interface from kernel to app and command access.

**Comment by vygr** [comment]
Now I added the dir list host call I can hardly object to this anymore. So yes, we should add a sys_pii:delete method and a handler in the main.c for it.

**Comment by vygr** [comment]
You will need these for the Windows build of main.c.

I normally have these unzipped in the root of the ChrysaLisp folder. If not you may need to fiddle with the path configs in VStudio.
[windows.zip](https://github.com/vygr/ChrysaLisp/files/4807681/windows.zip)

**Comment by vygr** [comment]
Created and pushed a new branch 'host-delete' spliced over from your clone Frank.

**Comment by vygr** [comment]
Martyn Bliss has got the (pii-remove) function working on Windows now, so this is done :)
