### ISSUE TITLE
Suggestion: Locate shared includes (libraries) in standard location

### ISSUE THREAD

**Issue by FrankC01** [vygr/ChrysaLisp#97]
There really can be two kinds:

- Those that are local to the class or app
- Those that are general in nature

For the latter I would suggest a `lib/` directory as standard where libraries follow a naming standard lib/NAME/LIBNAME.INC.

For example:
```
lib/argparse/argparse.inc
lib/options/options.inc 
```

**Comment by vygr** [comment]
I would be happy with the lib/ folder at the top level.

**Comment by vygr** [comment]
I would be happy with the lib/ folder at the top level.
